#ifndef ATTRACTIVITY_H
#define ATTRACTIVITY_H

enum ATTRACTIVITY{
    ATTRACTIVITY_UNKNOWN    = -1,
    ATTRACTIVITY_LOW        = 1,
    ATTRACTIVITY_STANDARD   = 2,
    ATTRACTIVITY_HIGH       = 4,
    ATTRACTIVITY_VERY_HIGH  = 8
};

#endif // ATTRACTIVITY_H
